// <auto-generated />
namespace RegistrationPractice.Migrations.Item
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class serialnumbertotalstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(serialnumbertotalstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201811292008596_serialnumbertotalstable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
