// <auto-generated />
namespace RegistrationPractice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class reward100012343423 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reward100012343423));
        
        string IMigrationMetadata.Id
        {
            get { return "201806212021533_reward100012343423"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
